In [1]:
L = ['red', 'yellow', 'orange', 'green', 'blue', 'purple']

In [2]:
print(L)

['red', 'yellow', 'orange', 'green', 'blue', 'purple']


In [3]:
L[0]

'red'

In [4]:
L[-1]

'purple'

In [5]:
L[2:4]

['orange', 'green']

In [6]:
L[:5]

['red', 'yellow', 'orange', 'green', 'blue']

In [7]:
L[:-1]

['red', 'yellow', 'orange', 'green', 'blue']

In [8]:
len(L)

6

In [9]:
print(sorted(L))

['blue', 'green', 'orange', 'purple', 'red', 'yellow']


In [10]:
print(L)

['red', 'yellow', 'orange', 'green', 'blue', 'purple']


In [11]:
L.append('black')

In [12]:
print(L)

['red', 'yellow', 'orange', 'green', 'blue', 'purple', 'black']


In [13]:
L = sorted(L)

In [14]:
print(L)

['black', 'blue', 'green', 'orange', 'purple', 'red', 'yellow']


In [15]:
L.insert(0, 'white')

In [16]:
print(L)

['white', 'black', 'blue', 'green', 'orange', 'purple', 'red', 'yellow']


In [22]:
L2 = ['pink', 'maroon', 'cyan']
L.extend(L2)

In [23]:
print(L)

['white', 'black', 'blue', 'green', 'orange', 'purple', 'red', 'yellow', 'pink', 'maroon', 'cyan']


In [24]:
L.reverse()

In [25]:
print(L)

['cyan', 'maroon', 'pink', 'yellow', 'red', 'purple', 'orange', 'green', 'blue', 'black', 'white']


In [26]:
L = sorted(L)

In [27]:
print(L)

['black', 'blue', 'cyan', 'green', 'maroon', 'orange', 'pink', 'purple', 'red', 'white', 'yellow']


In [28]:
for x in L:
    print(x)

black
blue
cyan
green
maroon
orange
pink
purple
red
white
yellow


In [1]:
k_array = [0.1, 0.2, 0.3]

In [2]:
print(k_array)

[0.1, 0.2, 0.3]


In [5]:
for x in range(len(k_array)):
    print(k_array[x])

0.1
0.2
0.3


In [1]:
import numpy as np

In [2]:
test_list = np.zeros(5)

In [4]:
for x in range(len(test_list)):
    test_list[x] = x
print(test_list)

[0. 1. 2. 3. 4.]


In [5]:
new_test = test_list - test_list
print(new_test)

[0. 0. 0. 0. 0.]


In [3]:
matrix = np.zeros((5, 5))

In [4]:
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
matrix[1][2] = 5
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
matrix.T

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])