In [1]:
import numpy as np

In [2]:
matrix = np.zeros((6, 6))
print(matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
for i in range(6):
    for j in range(6):
        matrix[i][j] = i+10-j
print(matrix)

[[10.  9.  8.  7.  6.  5.]
 [11. 10.  9.  8.  7.  6.]
 [12. 11. 10.  9.  8.  7.]
 [13. 12. 11. 10.  9.  8.]
 [14. 13. 12. 11. 10.  9.]
 [15. 14. 13. 12. 11. 10.]]


In [15]:
a_matrix = np.matrix(matrix)
print(a_matrix)
print(np.linalg.det(a_matrix))

[[10.  9.  8.  7.  6.  5.]
 [11. 10.  9.  8.  7.  6.]
 [12. 11. 10.  9.  8.  7.]
 [13. 12. 11. 10.  9.  8.]
 [14. 13. 12. 11. 10.  9.]
 [15. 14. 13. 12. 11. 10.]]
3.130954561673868e-59


In [5]:
inv = a_matrix.I
print(inv)


[[-5.60852003e+14  5.31480701e+14  4.26583195e+14 -1.04897507e+14
  -3.91617359e+14  9.93029732e+13]
 [ 5.66446537e+14  5.10501200e+14 -7.90227885e+14 -7.37779132e+14
  -1.02799557e+15  1.47905485e+15]
 [ 5.51061569e+14 -1.51052410e+15  2.09795014e+14  5.94419205e+14
   1.46856510e+15 -1.31331679e+15]
 [-5.55257470e+14  4.47562696e+14  6.29385041e+13  1.78325762e+14
   4.40569529e+14 -5.74139021e+14]
 [-4.19590027e+12 -1.06296140e+15  2.72733518e+14  1.33569492e+15
   7.83234718e+14 -1.32450585e+15]
 [ 2.79726685e+12  1.08394090e+15 -1.81822345e+14 -1.26576325e+15
  -1.27275642e+15  1.63360384e+15]]


In [6]:
print(inv*a_matrix)

[[ 22.    20.25  18.75  17.    15.25  13.  ]
 [-36.   -40.   -36.   -32.   -28.   -26.  ]
 [ 24.    16.    20.    20.    20.    18.  ]
 [  4.     4.     4.     2.     4.     3.  ]
 [-10.    -6.     0.    -4.    -2.    -1.  ]
 [  0.    -4.     2.     0.     2.    -2.  ]]


In [7]:
print(a_matrix*inv)

[[-0.16992188  0.          0.5         3.          2.          2.        ]
 [-0.86328125 -2.         -0.125       0.          2.          2.        ]
 [ 0.9453125  -1.         -0.25        2.          1.          0.        ]
 [-0.74609375 -1.          0.25        4.          0.          2.        ]
 [-0.5         0.          0.          4.          0.          8.        ]
 [-0.25        0.         -2.          4.          0.          0.        ]]


In [8]:
mtx = np.matrix('3 4; 1 5')

In [9]:
print(mtx)

[[3 4]
 [1 5]]


In [10]:
print(mtx*mtx.I)
print(mtx.I*mtx)

[[1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00]]
[[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]


In [14]:
print(np.linalg.det(mtx))

11.000000000000002
